{% set version = "1.2.2" %}

package:
  name: libwebp
  version: {{ version }}

source:
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-{{ version }}.tar.gz
  sha256: 7656532f837af5f4cec3ff6bafe552c044dc39bf453587bd5b77450802f4aee6

build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libwebp
    - {{ pin_compatible('libwebp-base') }}
    # autotools to CMake ABI break
    - libwebp-base <1.2.3

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [not win]
    - make                 # [not win]
  host:
    - giflib   # [not win]
    - jpeg     # [not win]
    - libpng   # [not win]
    - libtiff  # [not win]
    - libwebp-base {{ version }}
  run:
    - giflib   # [not win]
    - jpeg     # [not win]
    - libpng   # [not win]
    - libtiff  # [not win]
    - libwebp-base {{ version }}

test:
  source_files:
    - examples/test.webp
  commands:
    - test -f $PREFIX/bin/cwebp  # [not win]
    - test -f $PREFIX/bin/dwebp  # [not win]
    - dwebp examples/test.webp  # [not win]
    - if not exist %LIBRARY_BIN%\\cwebp.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\dwebp.exe exit 1  # [win]
    - dwebp examples\\test.webp  # [win]

about:
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_file: COPYING
  summary: WebP image library
  description: |
    WebP is a method of lossy and lossless compression that can be used on a large variety of photographic,
    translucent and graphical images found on the web. The degree of lossy compression is adjustable so a
    user can choose the trade-off between file size and image quality.
    libwebp-base provides the headers and shared libraries. For cwebp and dwep,
    binaries install libwebp.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
